SELECT
    p.PROJECT_ID,
    p.GIT_LINK,

    gc.COMMIT_HASH,
    gc.COMMITTER_DATE       AS CREATION_COMMIT_DATE,

    si.RULE,
    si.TYPE,
    si.SEVERITY,
    si.STATUS,
    si.COMPONENT,
    si.MESSAGE              AS ACTION_MESSAGE,
    si.START_LINE,
    si.END_LINE,
    si.EFFORT               AS EFFORT_MINUTES,

    sm.SQALE_INDEX,
    sm.SQALE_DEBT_RATIO,
    sm.CODE_SMELLS,
    sm.BUGS,
    sm.VULNERABILITIES,
    sm.BLOCKER_VIOLATIONS,
    sm.CRITICAL_VIOLATIONS,
    sm.MAJOR_VIOLATIONS,
    sm.MINOR_VIOLATIONS,
    sm.INFO_VIOLATIONS,
    sm.LINE_COVERAGE,
    sm.SQALE_RATING,
    sm.SECURITY_RATING,
    sm.RELIABILITY_RATING,
    sm.COGNITIVE_COMPLEXITY,
    sm.COMPLEXITY           AS cyclomatic_complexity,

    sr.DESCRIPTION

FROM SONAR_ISSUES si

JOIN SONAR_ANALYSIS sa
  ON sa.ANALYSIS_KEY = si.CREATION_ANALYSIS_KEY
 AND sa.REVISION IS NOT NULL

JOIN GIT_COMMITS gc
  ON gc.COMMIT_HASH = sa.REVISION

JOIN PROJECTS p
  ON p.PROJECT_ID = si.PROJECT_ID

LEFT JOIN SONAR_MEASURES sm
  ON sm.ANALYSIS_KEY = si.CREATION_ANALYSIS_KEY

LEFT JOIN SONAR_RULES sr
  ON sr.PLUGIN_NAME = substr(si.RULE, 1, instr(si.RULE, ':') - 1)
  AND sr.PLUGIN_RULE_KEY = substr(si.RULE, instr(si.RULE, ':') + 1)

WHERE si.STATUS = 'OPEN'

ORDER BY
    CASE si.SEVERITY
        WHEN 'BLOCKER'  THEN 1
        WHEN 'CRITICAL' THEN 2
        WHEN 'MAJOR'    THEN 3
        WHEN 'MINOR'    THEN 4
        ELSE 5
    END