import os
import subprocess
from datetime import datetime, timezone
from pathlib import Path
import tempfile
from state import PipelineState
from git import Repo
from github import Github
from checkpoint import write_header, write_footer


def _get_github_client() -> Github:
    return Github(os.environ["GITHUB_TOKEN"])


def _parse_github_repo(git_link: str) -> str:
    link = git_link.rstrip("/").removesuffix(".git")
    if link.startswith("git@github.com:"):
        return link.replace("git@github.com:", "")
    if "github.com/" in link:
        return link.split("github.com/", 1)[1]
    raise ValueError(f"Cannot parse GitHub repo from: {git_link}")


def _build_commit_message(rule: str, file: str, changelog: str) -> str:
    return "\n".join(
        [
            f"fix({file}): resolve SonarQube {rule}",
            "",
            changelog if changelog else f"Automated fix for rule {rule}.",
            "",
            "Generated by TD Agent. Review before merging.",
        ]
    )


_SEVERITY_ORDER = ["BLOCKER", "CRITICAL", "MAJOR", "MINOR", "INFO"]


def _build_pr_body(approved: list, failed: list, commit_count: int) -> str:
    resolved_issues = [i for item in approved for i in item["patch"].get("issues", [])]
    failed_issues = [i for item in failed for i in item["task"].get("issues", [])]
    total = len(resolved_issues) + len(failed_issues)

    lines = ["## Technical Debt Agent — Automated Fix PR", ""]

    lines += [
        "### Summary",
        f"- Resolved: {len(resolved_issues)} of {total} issue(s) across {len({item['patch']['target_file'] for item in approved})} file(s)",
        f"- Failed: {len(failed_issues)} issue(s)",
        f"- Commits: {commit_count}",
        "",
    ]

    if resolved_issues:
        severity_counts: dict[str, int] = {}
        for issue in resolved_issues:
            sev = issue.get("severity", "INFO")
            severity_counts[sev] = severity_counts.get(sev, 0) + 1

        lines += ["### Severity breakdown (resolved)", ""]
        for sev in _SEVERITY_ORDER:
            if sev in severity_counts:
                lines.append(f"- {sev}: {severity_counts[sev]}")
        lines.append("")

    lines += [
        "---",
        "> This PR was opened automatically. Do not merge without review.",
    ]
    return "\n".join(lines)


def vcs_setup(state: PipelineState) -> dict:
    """Create feature branch on an existing local clone, or clone if project_dir not set."""
    report = state["report"]
    timestamp = datetime.now(timezone.utc).strftime("%Y%m%d-%H%M%S")
    branch_name = f"td-agent/fix-{timestamp}"

    project_dir = state.get("project_dir")
    if project_dir:
        repo = Repo(project_dir)
        repo_dir = project_dir
        print(f"[VCS] Using local repo: {repo_dir}")
    else:
        git_link = report["git_link"]
        commit_hash = report["commit_hash"]
        repo_dir = tempfile.mkdtemp(prefix="td_agent_")
        repo = Repo.clone_from(git_link, repo_dir)
        repo.git.checkout(commit_hash)
        print(f"[VCS] Cloned  : {git_link} → {repo_dir}")
        print(f"[VCS] Checkout: {commit_hash[:12]}")

    default_branch = repo.git.symbolic_ref("refs/remotes/origin/HEAD").split("/")[-1]
    repo.git.checkout(default_branch)
    print(f"[VCS] Checked out: {default_branch}")
    repo.git.checkout("-b", branch_name)
    print(f"[VCS] Branch  : {branch_name}")

    checkpoint_path = state.get("checkpoint_path")
    if checkpoint_path:
        write_header(
            Path(checkpoint_path),
            branch_name,
            datetime.now(timezone.utc).isoformat(),
        )

    return {
        "repo_path": repo_dir,
        "branch_name": branch_name,
        "last_event": "vcs_ready",
    }


def vcs_commit_chunk(state: PipelineState) -> dict:
    """Commit the current file's patches immediately after all its functions are processed."""
    repo_path = state["repo_path"]
    ctx = state.get("context") or {}
    file_path = ctx.get("file_path", "")
    approved = state.get("approved") or []

    file_entries = [
        item for item in approved if item["patch"]["target_file"] == file_path
    ]

    if not file_entries:
        print(f"[VCS] No approved patches for {Path(file_path).name} — skipping commit")
        return {"last_event": "chunk_committed"}

    repo = Repo(repo_path)
    repo.index.add([file_path])

    if not repo.index.diff("HEAD"):
        print(f"[VCS] No changes to commit for {Path(file_path).name} — skipping")
        return {"last_event": "chunk_committed"}

    rule_keys = [
        k for item in file_entries for k in (item["patch"].get("rule_key") or [])
    ]
    rule_str = rule_keys[0] if rule_keys else "multiple"
    changelog = "\n".join(
        item.get("changelog_entry", "")
        for item in file_entries
        if item.get("changelog_entry")
    )

    msg = _build_commit_message(
        rule=rule_str,
        file=Path(file_path).name,
        changelog=changelog,
    )
    commit = repo.index.commit(msg)
    print(f"[VCS] Committed {commit.hexsha[:12]}: {Path(file_path).name}")

    return {"last_event": "chunk_committed"}


def vcs_finalize(state: PipelineState) -> dict:
    """Push the feature branch and open a pull request."""
    assert state["repo_path"] and state["branch_name"]
    report = state["report"]
    approved = state.get("approved") or []
    failed = state.get("failed") or []
    repo_path = state["repo_path"]
    branch_name = state["branch_name"]

    repo = Repo(repo_path)
    commit_count = len({item["patch"]["target_file"] for item in approved})

    # ── Push branch ──────────────────────────────────────────
    origin = repo.remote("origin")
    origin.push(refspec=f"{branch_name}:{branch_name}")
    print(f"[VCS] Pushed branch: {branch_name}")

    # ── Open PR ──────────────────────────────────────────────
    gh = _get_github_client()
    gh_repo = gh.get_repo(_parse_github_repo(report["git_link"]))
    base_branch = gh_repo.default_branch

    pr = gh_repo.create_pull(
        title=f"[TD Agent] Fix {len(approved)} issue(s) — {branch_name.split('/')[-1]}",
        body=_build_pr_body(approved, failed, commit_count),
        head=branch_name,
        base=base_branch,
    )
    print(f"[VCS] PR opened: {pr.html_url}")

    checkpoint_path = state.get("checkpoint_path")
    if checkpoint_path:
        write_footer(
            Path(checkpoint_path),
            datetime.now(timezone.utc).isoformat(),
            pr.html_url,
        )

    return {
        "vcs_mode": "done",
        "pr_url": pr.html_url,
        "pr_number": pr.number,
    }
