import os
import subprocess
from datetime import datetime, timezone
from pathlib import Path

import tempfile

from state import PipelineState

from git import Repo
from github import Github


def _get_github_client() -> Github:
    return Github(os.environ["GITHUB_TOKEN"])


def _parse_github_repo(git_link: str) -> str:
    link = git_link.rstrip("/").removesuffix(".git")
    if link.startswith("git@github.com:"):
        return link.replace("git@github.com:", "")
    if "github.com/" in link:
        return link.split("github.com/", 1)[1]
    raise ValueError(f"Cannot parse GitHub repo from: {git_link}")


def _build_commit_message(rule: str, file: str, changelog: str) -> str:
    return "\n".join(
        [
            f"fix({file}): resolve SonarQube {rule}",
            "",
            changelog if changelog else f"Automated fix for rule {rule}.",
            "",
            "Generated by TD Agent. Review before merging.",
        ]
    )


def _build_pr_body(approved: list, failed: list, commits: list) -> str:
    lines = ["## Technical Debt Agent — Automated Fix PR", ""]

    lines += [
        "### Summary",
        f"- ✅ Resolved: {len(approved)} issue(s)",
        f"- ❌ Failed:   {len(failed)} issue(s)",
        f"- 🔀 Commits:  {len(commits)}",
        "",
    ]

    if approved:
        lines += ["### ✅ Resolved Issues", ""]
        for item in approved:
            patch = item["patch"]
            lines.append(
                f"- `{patch['rule_key']}` in `{Path(patch['target_file']).name}`"
                + (
                    f" — {item['changelog_entry']}"
                    if item.get("changelog_entry")
                    else ""
                )
            )
        lines.append("")

    if failed:
        lines += ["### ❌ Failed Issues (exhausted retries)", ""]
        for item in failed:
            task = item["task"]
            lines.append(f"- `{task['rule_key']}` in `{Path(task['component']).name}`")
            for r in item.get("rejection_history", []):
                lines.append(f"  - Attempt {r['attempt']}: {r['reason']}")
        lines.append("")

    lines += [
        "---",
        "> ⚠️ This PR was opened automatically. Do not merge without review.",
    ]
    return "\n".join(lines)


def vcs_setup(state: PipelineState) -> dict:
    """Create feature branch on an existing local clone, or clone if project_dir not set."""
    report = state["report"]
    timestamp = datetime.now(timezone.utc).strftime("%Y%m%d-%H%M%S")
    branch_name = f"td-agent/fix-{timestamp}"

    project_dir = state.get("project_dir")
    if project_dir:
        repo = Repo(project_dir)
        repo_dir = project_dir
        print(f"[VCS] Using local repo: {repo_dir}")
    else:
        git_link = report["git_link"]
        commit_hash = report["commit_hash"]
        repo_dir = tempfile.mkdtemp(prefix="td_agent_")
        repo = Repo.clone_from(git_link, repo_dir)
        repo.git.checkout(commit_hash)
        print(f"[VCS] Cloned  : {git_link} → {repo_dir}")
        print(f"[VCS] Checkout: {commit_hash[:12]}")

    repo.git.checkout("-b", branch_name)
    print(f"[VCS] Branch  : {branch_name}")

    return {
        "repo_path": repo_dir,
        "branch_name": branch_name,
        "last_event": "vcs_ready",
    }


def vcs_finalize(state: PipelineState) -> dict:
    """
    Commit all approved patches as atomic commits, push the feature branch,
    and open a pull request. Called once after all chunks reach terminal state.
    """
    assert state["repo_path"] and state["branch_name"]
    report = state["report"]
    approved = state.get("approved") or []
    failed = state.get("failed") or []
    repo_path = state["repo_path"]
    branch_name = state["branch_name"]

    repo = Repo(repo_path)

    # ── Batch commit all approved patches ────────────────────
    commits = []
    for item in approved:
        patch = item["patch"]
        target_file = patch["target_file"]  # repo-relative path
        rule_key = patch.get("rule_key", [])
        rule_str = (
            rule_key[0] if isinstance(rule_key, list) and rule_key else str(rule_key)
        )
        changelog = item.get("changelog_entry", "")

        repo.index.add([target_file])
        msg = _build_commit_message(
            rule=rule_str,
            file=Path(target_file).name,
            changelog=changelog,
        )
        commit = repo.index.commit(msg)
        print(f"[VCS] Committed {commit.hexsha[:12]}: {Path(target_file).name}")
        commits.append({"sha": commit.hexsha, "message": msg})

    # ── Push branch ──────────────────────────────────────────
    origin = repo.remote("origin")
    origin.push(refspec=f"{branch_name}:{branch_name}")
    print(f"[VCS] Pushed branch: {branch_name}")

    # ── Open PR ──────────────────────────────────────────────
    gh = _get_github_client()
    gh_repo = gh.get_repo(_parse_github_repo(report["git_link"]))
    base_branch = gh_repo.default_branch

    pr = gh_repo.create_pull(
        title=f"[TD Agent] Fix {len(approved)} issue(s) — {branch_name.split('/')[-1]}",
        body=_build_pr_body(approved, failed, commits),
        head=branch_name,
        base=base_branch,
    )
    print(f"[VCS] PR opened: {pr.html_url}")

    return {
        "vcs_mode": "done",
        "pr_url": pr.html_url,
        "pr_number": pr.number,
    }


