import os
import subprocess
from datetime import datetime, timezone
from pathlib import Path
import tempfile
from state import PipelineState
from git import Repo
from github import Github, GithubException
from checkpoint import write_header, write_footer, read_checkpoint_stats


def _get_github_client() -> Github:
    return Github(os.environ["GITHUB_TOKEN"])


def _parse_github_repo(git_link: str) -> str:
    link = git_link.rstrip("/").removesuffix(".git")
    if link.startswith("git@github.com:"):
        return link.replace("git@github.com:", "")
    if "github.com/" in link:
        return link.split("github.com/", 1)[1]
    raise ValueError(f"Cannot parse GitHub repo from: {git_link}")


def _build_commit_message(rule: str, file: str, changelog: str) -> str:
    return "\n".join(
        [
            f"fix({file}): resolve SonarQube {rule}",
            "",
            changelog if changelog else f"Automated fix for rule {rule}.",
            "",
            "Generated by TD Agent. Review before merging.",
        ]
    )


_SEVERITY_ORDER = ["BLOCKER", "CRITICAL", "MAJOR", "MINOR", "INFO"]


def _build_pr_body_from_stats(resolved: list[dict], failed: list[dict], commit_count: int) -> str:
    total = len(resolved) + len(failed)
    lines = ["## Technical Debt Agent — Automated Fix PR", ""]
    lines += [
        "### Summary",
        f"- Resolved: {len(resolved)} of {total} issue(s) across {len({i.get('file') for i in resolved})} file(s)",
        f"- Failed: {len(failed)} issue(s)",
        f"- Commits: {commit_count}",
        "",
    ]
    if resolved:
        severity_counts: dict[str, int] = {}
        for issue in resolved:
            sev = issue.get("severity", "INFO")
            severity_counts[sev] = severity_counts.get(sev, 0) + 1
        lines += ["### Severity breakdown (resolved)", ""]
        for sev in _SEVERITY_ORDER:
            if sev in severity_counts:
                lines.append(f"- {sev}: {severity_counts[sev]}")
        lines.append("")

    first_try = sum(1 for i in resolved if len(i.get("rejection_reasons", [])) == 0)
    multi_attempt = len(resolved) - first_try
    no_fix_needed = sum(1 for i in failed if len(i.get("rejection_reasons", [])) == 0)
    exhausted = len(failed) - no_fix_needed
    total_attempts = (
        sum(len(i.get("rejection_reasons", [])) + 1 for i in resolved)
        + sum(len(i.get("rejection_reasons", [])) for i in failed if i.get("rejection_reasons"))
        + no_fix_needed
    )
    lines += ["### Attempt statistics", ""]
    lines.append(f"- Total LLM attempts: {total_attempts}")
    lines.append(f"- Resolved first try: {first_try}")
    if multi_attempt:
        lines.append(f"- Resolved after retries: {multi_attempt}")
    lines.append(f"- Exhausted retries: {exhausted}")
    if no_fix_needed:
        lines.append(f"- No fix needed (triage): {no_fix_needed}")
    lines.append("")

    lines += ["---", "> This PR was opened automatically. Do not merge without review."]
    return "\n".join(lines)


def _build_pr_body(approved: list, failed: list, commit_count: int) -> str:
    resolved_issues = [i for item in approved for i in item["patch"].get("issues", [])]
    failed_issues = [i for item in failed for i in item["task"].get("issues", [])]
    total = len(resolved_issues) + len(failed_issues)

    lines = ["## Technical Debt Agent — Automated Fix PR", ""]

    lines += [
        "### Summary",
        f"- Resolved: {len(resolved_issues)} of {total} issue(s) across {len({item['patch']['target_file'] for item in approved})} file(s)",
        f"- Failed: {len(failed_issues)} issue(s)",
        f"- Commits: {commit_count}",
        "",
    ]

    if resolved_issues:
        severity_counts: dict[str, int] = {}
        for issue in resolved_issues:
            sev = issue.get("severity", "INFO")
            severity_counts[sev] = severity_counts.get(sev, 0) + 1

        lines += ["### Severity breakdown (resolved)", ""]
        for sev in _SEVERITY_ORDER:
            if sev in severity_counts:
                lines.append(f"- {sev}: {severity_counts[sev]}")
        lines.append("")

    lines += [
        "---",
        "> This PR was opened automatically. Do not merge without review.",
    ]
    return "\n".join(lines)


def vcs_setup(state: PipelineState) -> dict:
    """Create feature branch on an existing local clone, or clone if project_dir not set."""
    report = state["report"]
    resume_branch = state.get("resume_branch")

    project_dir = state.get("project_dir")
    if project_dir:
        repo = Repo(project_dir)
        repo_dir = project_dir
        print(f"[VCS] Using local repo: {repo_dir}")
    else:
        git_link = report["git_link"]
        commit_hash = report["commit_hash"]
        repo_dir = tempfile.mkdtemp(prefix="td_agent_")
        repo = Repo.clone_from(git_link, repo_dir)
        repo.git.checkout(commit_hash)
        print(f"[VCS] Cloned  : {git_link} → {repo_dir}")
        print(f"[VCS] Checkout: {commit_hash[:12]}")

    if resume_branch:
        repo.git.checkout(resume_branch)
        branch_name = resume_branch
        print(f"[VCS] Resumed branch: {branch_name}")

        # Window B: commit any uncommitted tracked changes left by the previous run
        if repo.is_dirty(index=True, working_tree=True, untracked_files=False):
            repo.git.add("-u")
            repo.index.commit("resume: commit leftover patches from previous run")
            print("[VCS] Committed leftover uncommitted patches")
    else:
        timestamp = datetime.now(timezone.utc).strftime("%Y%m%d-%H%M%S")
        branch_name = f"td-agent/fix-{timestamp}"
        default_branch = repo.git.symbolic_ref("refs/remotes/origin/HEAD").split("/")[-1]
        repo.git.checkout(default_branch)
        print(f"[VCS] Checked out: {default_branch}")
        repo.git.checkout("-b", branch_name)
        print(f"[VCS] Branch  : {branch_name}")

        checkpoint_path = state.get("checkpoint_path")
        if checkpoint_path:
            write_header(
                Path(checkpoint_path),
                branch_name,
                datetime.now(timezone.utc).isoformat(),
            )

    return {
        "repo_path": repo_dir,
        "branch_name": branch_name,
        "last_event": "vcs_ready",
    }


def vcs_commit_chunk(state: PipelineState) -> dict:
    """Commit the current file's patches immediately after all its functions are processed."""
    repo_path = state["repo_path"]
    ctx = state.get("context") or {}
    file_path = ctx.get("file_path", "")
    approved = state.get("approved") or []

    file_entries = [
        item for item in approved if item["patch"]["target_file"] == file_path
    ]

    if not file_entries:
        print(f"[VCS] No approved patches for {Path(file_path).name} — skipping commit")
        return {"last_event": "chunk_committed"}

    repo = Repo(repo_path)
    repo.index.add([file_path])

    if not repo.index.diff("HEAD"):
        print(f"[VCS] No changes to commit for {Path(file_path).name} — skipping")
        return {"last_event": "chunk_committed"}

    rule_keys = [
        k for item in file_entries for k in (item["patch"].get("rule_key") or [])
    ]
    rule_str = rule_keys[0] if rule_keys else "multiple"
    changelog = "\n".join(
        item.get("changelog_entry", "")
        for item in file_entries
        if item.get("changelog_entry")
    )

    msg = _build_commit_message(
        rule=rule_str,
        file=Path(file_path).name,
        changelog=changelog,
    )
    commit = repo.index.commit(msg)
    print(f"[VCS] Committed {commit.hexsha[:12]}: {Path(file_path).name}")

    return {"last_event": "chunk_committed"}


def vcs_finalize(state: PipelineState) -> dict:
    """Push the feature branch and open a pull request."""
    assert state["repo_path"] and state["branch_name"]
    report = state["report"]
    approved = state.get("approved") or []
    failed = state.get("failed") or []
    repo_path = state["repo_path"]
    branch_name = state["branch_name"]

    repo = Repo(repo_path)
    checkpoint_path = state.get("checkpoint_path")

    # ── Build PR body always from checkpoint (has full attempt data) ──────────
    if checkpoint_path:
        stats = read_checkpoint_stats(Path(checkpoint_path))
        approved_issues = stats["resolved"]
        failed_issues = stats["failed"]
        commit_count = len({i.get("file", "") for i in approved_issues})
        pr_body = _build_pr_body_from_stats(approved_issues, failed_issues, commit_count)
        pr_issue_count = len(approved_issues)
        print(f"[VCS] PR body from checkpoint ({len(approved_issues)} resolved, {len(failed_issues)} failed)")
    else:
        commit_count = len({item["patch"]["target_file"] for item in approved})
        pr_body = _build_pr_body(approved, failed, commit_count)
        pr_issue_count = len([i for item in approved for i in item["patch"].get("issues", [])])

    # ── Push branch ──────────────────────────────────────────
    origin = repo.remote("origin")
    origin.push(refspec=f"{branch_name}:{branch_name}")
    print(f"[VCS] Pushed branch: {branch_name}")

    # ── Open PR ──────────────────────────────────────────────
    gh = _get_github_client()
    gh_repo = gh.get_repo(_parse_github_repo(report["git_link"]))
    base_branch = gh_repo.default_branch

    try:
        pr = gh_repo.create_pull(
            title=f"[TD Agent] Fix {pr_issue_count} issue(s) — {branch_name.split('/')[-1]}",
            body=pr_body,
            head=branch_name,
            base=base_branch,
        )
        print(f"[VCS] PR opened: {pr.html_url}")
    except GithubException as exc:
        if "A pull request already exists" in str(exc):
            owner = gh_repo.owner.login
            existing = list(gh_repo.get_pulls(state="open", head=f"{owner}:{branch_name}"))
            if existing:
                pr = existing[0]
                print(f"[VCS] PR already exists: {pr.html_url}")
            else:
                raise
        elif exc.status == 403:
            print(f"[VCS] GitHub 403 — cannot create PR ({exc.data.get('message', '')}). "
                  "Check GITHUB_TOKEN scopes.")
            if checkpoint_path:
                write_footer(Path(checkpoint_path), datetime.now(timezone.utc).isoformat(), None)
            return {"vcs_mode": "done", "pr_url": None, "pr_number": None}
        else:
            raise

    if checkpoint_path:
        write_footer(
            Path(checkpoint_path),
            datetime.now(timezone.utc).isoformat(),
            pr.html_url,
        )

    return {
        "vcs_mode": "done",
        "pr_url": pr.html_url,
        "pr_number": pr.number,
    }
